---
AWSTemplateFormatVersion: '2010-09-09'

Description:
  Create s3 and Cloudfront for our static website 

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: gisbucket1
      WebsiteConfiguration: 
        IndexDocument: index.html

  BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::gisbucket1/*'
# Outputs:
#   WebsiteURL:
#     Value: !GetAtt 
#       - S3Bucket
#       - WebsiteURL
#     Description: This URL is used for my static website
